
lake: 'HALLWIL'
path_models: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/MODEL_RESULTS'
path_figures: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/FIGURES'
path_outfiles: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/OUTFILES'
model_names: ['EAWAG_INPUTS_BASE']
  #model_names: ['EAWAG_RESULTS']
time_span: ['01-01-1981', '31-12-2021 00:00']

writedata: True
timeaverage: ['M', 'Y']

makeplots: False
plot:
  colormesh: []
  timeseries: ['I_RAD', 'I_VAP', 'I_KL']
  figformat: 'png'
  save: True



