
lake: 'HALLWIL'
path_obs: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/HalwillData/Raw'
path_models: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/MODEL_RESULTS'
path_figures: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/FIGURES'
path_outfiles: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/OUTFILES'
model_names: ['EAWAG_INPUTS_BASE', 'EIB_LIGHT_KCPD_P0_NOBRIGHT', 'EIB_LIGHT_KCPD_P1_NOBRIGHT', 'EIB_LIGHT_KCPD_P2_NOBRIGHT',   'EIB_LIGHT_KCPD_P0',  'EIB_LIGHT_KCPD_P1', 'EIB_LIGHT_KCPD_P2','EAWAG_INPUTS_BASE_NOBRIGHT']
time_span: ['01-01-1986', '12-31-2021']

file_wtempprof: 'Temperature_bafu85_98probes20.csv'
file_secchi: 'secchi8519.xlsx'
file_bathymetry: 'Bathymetry.dat'

timeaverage: ['M', 'Y', 'YS']
date_periods: ['1996', '2008']

makeplots: True
plot:
  colormesh: []
  timeseries: ['O_SD', 'O_ST', 'O_MN2', 'O_HC', 'O_TEMP0', 'O_TEMPB']
    #timeseries: [['I_SD', 'O_SD'], 'HA', 'HW', 'HK', 'HV', ['ST', 'O_ST'], ['TEMPB', 'O_TEMPB'], ['HC', 'O_HC'],['TEMP0', 'O_TEMP0'], ['MN2', 'O_MN2'], 'O_SD']
    #timeseries: ['HA', 'HW', 'HK', 'HV', 'O_TEMP0', 'O_SD', 'O_ST']
  profiles: [] #['O_TEMPI','O_TEMPP'], ['O_TEMPI', 'O_N2'], ['TEMP', 'O_TEMPP']]
  figformat: 'png'
  save: True

write:
  model: False
  obs: False
  stats: False
  append-m: True
  append-o: True
  append-s: False

stats:
  vars: [] #['TEMP0', 'O_TEMP0'], ['TEMP', 'O_TEMPP'], ['TEMPB', 'O_TEMPB']]
