# MAIN CONFIG
#
lake: 'Lake Hallwil'
date_interval: ['2000-01-01', '2019-01-01 00:00']

# PATHS
#
meta_path: '/home/cesar/Documentos/PhD/PY_projects/Simstrat-WorkflowModellingSwissLakes'
meteo_path: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/INPUTS/HALLWIL/MET_LUZ_2000_2022'
hydro_path: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/INPUTS/HALLWIL/15065_4410_2024-02-06_14-22-15/'
output_path: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/MODEL_RESULTS/HALLWIL/TEST_2000-2005flow'

# FILES
#
meta_file: 'Lakes.json'
meteo_file: 'order_117973_data.txt'
hydro_file : '2416_Abfluss_Stundenmittel_1985-01-01_2023-12-31.csv'

output_meteo: 'Forcing.csv'
output_hydro: ['Qin.csv', 'Qout.csv', 'Tin.csv', 'Sin.csv']

