# MAIN CONFIG
#
lake: 'Lake Hallwil'
date_interval: ['2000-01-01', '2005-01-01 00:00']

# PATHS
#
meta_path: '/home/cesar/Documents/PhD/PY_projects/Simstrat-WorkflowModellingSwissLakes'
meteo_path: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/Hallwil/Simulations/Hallwil/MET_LUZ_2000_2022'
output_path: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/Hallwil/Simulations/Hallwil'

# FILES
#
meteo_file: 'order_117973_data.txt'
meta_file: 'Lakes.json'
output_file: 'MeteoForcing2.csv'
