
lake: 'HALLWIL'
path_models: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/WaterClarity/Simulations/MODEL_RESULTS'
model_names: ['EAWAG_RESULTS', 'EAWAGINPUTS']
  #model_names: ['MY_TESTZURICH', 'TEST_ZURICH']
time_span: ['01-01-2000', '01-01-2005 00:00']

var: ['TEMP','SAL']

plot:
  colormesh: ['TEMP']
