
WINDU: ['U.dat', 'Water Velicity E-W (\si{\meter\per\second})', '2D']
WINDV: ['V.dat', 'Water Velocity N-S (\si{\meter\per\second})', '2D']
TEMP: ['T.dat', 'Temperature (\si{\degreeCelsius})', '2D']
SAL: ['S.dat', 'Salinity (\si{\permille})', '2D']
TKE: ['k.dat', 'TKE (\si{\joule\per\kilo\gram})']
EPS: ['eps.dat', 'EPS (\si{\watt\per\kilo\gram})']
NUH: ['nuh.dat', 'Turbulent diffusivity of temperature (\si{\joule\second\per\kilo\gram})']
NUM: ['num.dat', 'Turbulent diffusivity of momentum (\si{\square\meter\per\second})']
N2: ['NN.dat', 'Brunt-Väisälä frequency (\si{\per\square\second})']
B: ['B.dat','Production rate of boyancy (\si{\watt\per\kilo\gram})']
P: ['P.dat', 'Production rate of shear stress (\si{\watt\per\kilo\gram})']
Ps: ['Ps.dat', 'Production rate of seiche energy (\si{\watt\per\kilo\gram})']
HA: ['HA.dat', 'LW Radation in (\si{\watt\per\square\meter})', '1D']
HW: ['HW.dat', 'LW Radation out (\si{\watt\per\square\meter})', '1D']
HK: ['HK.dat', 'Sensible Heat (\si{\watt\per\square\meter})', '1D']
HV: ['HV.dat', 'Latent Heat (\si{\watt\per\square\meter})', '1D']
RAD0: ['Rad0.dat', 'Solar Radiation penetrating lake (\si{\watt\per\square\meter})', '1D']
ICE: ['TotalIceH.dat', 'Ice thickness (\si{\meter})', '1D']
BICE: ['BlackIceH', 'Black ice thickness (\si{\meter})', '1D']
WICE: ['WhiteIceH', 'White ice thickness (\si{\meter})', '1D']
SNOW: ['SnowH.dat', 'Snow heigh above ice (\si{\meter})', '1D']
WATH: ['WaterH.dat', 'Water depth (\si{\meter})', '1D']
QVERT: ['Qvert.dat', 'Vertical advection (\si{\cubic\meter\per\second})']
ESEI: ['Eseiche.dat', 'Total seiche energy (\si{\joule})', '1D']

T0: ['T.dat', 'Surface temperature (\si{\degreeCelsius})', '1D']
TB: ['T.dat', 'Bottom temperature (\si{\degreeCelsius})', '1D']

## INPUTS VARIABLES
I_KL: ['Absorption.dat', 'Light Absortion (\si{\per\meter})', '1D']
I_RAD: ['Forcing.dat', 'Solar Radiation (\si{\watt\per\square\meter\per\day})', '1D']
I_VAP: ['Forcing.dat', 'Vapor Pressure (\si{\hecto\pascal})', '1D']

O_TEMPP: ['', 'Temperature (\si{\degreeCelsius})', '2D']
O_TEMP0: ['', 'Temperature (\si{\degreeCelsius})', '1D']
O_SD: ['', 'Secchi disk depth (\si{\meter})', '1D']
